version: '3.8'
services:


  mysql:
    image: mysql:latest
    container_name: mysql-debezium
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: debezium
      MYSQL_USER: debezium
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - test-network
 

volumes:
  mysql-data:
    driver: local

networks:
  test-network:
    driver: bridge